### ISSUE TITLE
RNodeConf doesn't download .version file for --fw-version

### ISSUE THREAD

**Issue by faragher** [markqvist/Reticulum#398]
RNodeConf doesn't appear to download or otherwise generate the <firmware name>.zip.version file when downloading for --fw-version and thus fails out when trying to install legacy versions.

**Comment by markqvist** [comment]
Support for downloading and flashing older versions is currently incomplete, and (regrettably) needs to be handled manually, by placing files in the correct directories.

Unfortunately I will not have time to complete implementation of this feature within the foreseeable future.

With more and more boards and variants available, a more complete overhaul of the install system would be a welcome improvement, along with the ability to add custom repositories, so that different people could host their own firmware variants as well.

I'm going to close this for now, since I can't prioritise working on it, but a community effort to create a better install / bootstrap system would definitely be a good way forward!
